AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/build/distributions/app.zip
      Handler: aws_lambda_demo.demo.app.HandlerIntegerJava17
      Runtime: java17
      Description: Java function
      MemorySize: 2048
      Timeout: 240 # Set timeout to 240 seconds (4 minutes)
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0/5 * * * ? *) # Trigger every 5 minutes
            Enabled: True